In [51]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.7)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.5.20)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)

In [52]:
import yfinance as yf
import pandas as pd
tickers=['AAPL','MSFT','SPY']
data = yf.download(tickers, period="5y", interval="1d", auto_adjust=True, progress=False)
data.columns = [f"{ticker}_{metric}" for metric, ticker in data.columns]
data = data.reset_index()
data

,Date,AAPL_Close,MSFT_Close,SPY_Close,AAPL_High,MSFT_High,SPY_High,AAPL_Low,MSFT_Low,SPY_Low,AAPL_Open,MSFT_Open,SPY_Open,AAPL_Volume,MSFT_Volume,SPY_Volume
0,2021-06-28,131.377060,257.889679,399.526550,131.835195,258.062417,399.694777,129.983172,255.192934,398.049846,130.041655,255.461648,399.246173,62111300,19590000,53159600
1,2021-06-29,132.887924,260.461700,399.741547,133.043888,260.701625,400.545315,130.957920,257.179554,399.208800,131.396555,258.033669,399.909773,64556100,19937800,35970500
2,2021-06-30,133.501999,259.981812,400.078033,133.940634,260.423264,400.750969,132.439508,258.734218,399.255554,132.731937,259.780283,399.283592,63261400,21656500,64827900
3,2021-07-01,133.804230,260.653595,402.293060,133.862712,260.883913,402.451960,132.332344,258.734202,400.769608,133.151148,258.743779,400.835039,52485800,16725300,53441000
4,2021-07-02,136.426285,266.459808,405.367981,136.465268,266.795708,405.723145,134.272077,261.517376,402.377152,134.418283,261.824486,403.452000,78852600,26458000,57697700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,2026-06-22,297.010010,367.339996,744.390015,302.420013,381.630005,750.179993,296.760010,367.070007,743.130005,297.309998,375.739990,747.700012,44879900,45171100,46628100
1251,2026-06-23,294.299988,373.940002,733.580017,301.640015,377.220001,739.630005,294.179993,370.670013,732.299988,297.540009,372.380005,733.809998,52010900,40647600,66846800
1252,2026-06-24,293.079987,365.459991,733.239990,299.700012,378.880005,739.950012,292.940002,364.779999,730.840027,295.359985,371.570007,735.169983,53081900,44509900,57439500
1253,2026-06-25,275.149994,352.829987,734.299988,288.799988,364.230011,739.369995,273.750000,349.200012,729.599976,287.399994,362.769989,738.909973,107013700,66179000,53934400
1254,2026-06-26,283.779999,372.970001,728.989990,285.950012,376.609985,736.530029,274.209991,355.429993,716.580017,275.000000,357.149994,728.950012,261693600,186112200,70932800

In [53]:
data.shape

(1255, 16)

In [54]:
data.to_csv("stock_data.csv")

In [55]:
data

,Date,AAPL_Close,MSFT_Close,SPY_Close,AAPL_High,MSFT_High,SPY_High,AAPL_Low,MSFT_Low,SPY_Low,AAPL_Open,MSFT_Open,SPY_Open,AAPL_Volume,MSFT_Volume,SPY_Volume
0,2021-06-28,131.377060,257.889679,399.526550,131.835195,258.062417,399.694777,129.983172,255.192934,398.049846,130.041655,255.461648,399.246173,62111300,19590000,53159600
1,2021-06-29,132.887924,260.461700,399.741547,133.043888,260.701625,400.545315,130.957920,257.179554,399.208800,131.396555,258.033669,399.909773,64556100,19937800,35970500
2,2021-06-30,133.501999,259.981812,400.078033,133.940634,260.423264,400.750969,132.439508,258.734218,399.255554,132.731937,259.780283,399.283592,63261400,21656500,64827900
3,2021-07-01,133.804230,260.653595,402.293060,133.862712,260.883913,402.451960,132.332344,258.734202,400.769608,133.151148,258.743779,400.835039,52485800,16725300,53441000
4,2021-07-02,136.426285,266.459808,405.367981,136.465268,266.795708,405.723145,134.272077,261.517376,402.377152,134.418283,261.824486,403.452000,78852600,26458000,57697700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,2026-06-22,297.010010,367.339996,744.390015,302.420013,381.630005,750.179993,296.760010,367.070007,743.130005,297.309998,375.739990,747.700012,44879900,45171100,46628100
1251,2026-06-23,294.299988,373.940002,733.580017,301.640015,377.220001,739.630005,294.179993,370.670013,732.299988,297.540009,372.380005,733.809998,52010900,40647600,66846800
1252,2026-06-24,293.079987,365.459991,733.239990,299.700012,378.880005,739.950012,292.940002,364.779999,730.840027,295.359985,371.570007,735.169983,53081900,44509900,57439500
1253,2026-06-25,275.149994,352.829987,734.299988,288.799988,364.230011,739.369995,273.750000,349.200012,729.599976,287.399994,362.769989,738.909973,107013700,66179000,53934400
1254,2026-06-26,283.779999,372.970001,728.989990,285.950012,376.609985,736.530029,274.209991,355.429993,716.580017,275.000000,357.149994,728.950012,261693600,186112200,70932800

In [56]:
# from google.colab import files
# files.download("stock_data.csv")

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1255 entries, 0 to 1254
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1255 non-null   datetime64[ns]
 1   AAPL_Close   1255 non-null   float64
 2   MSFT_Close   1255 non-null   float64
 3   SPY_Close    1255 non-null   float64
 4   AAPL_High    1255 non-null   float64
 5   MSFT_High    1255 non-null   float64
 6   SPY_High     1255 non-null   float64
 7   AAPL_Low     1255 non-null   float64
 8   MSFT_Low     1255 non-null   float64
 9   SPY_Low      1255 non-null   float64
 10  AAPL_Open    1255 non-null   float64
 11  MSFT_Open    1255 non-null   float64
 12  SPY_Open     1255 non-null   float64
 13  AAPL_Volume  1255 non-null   int64
 14  MSFT_Volume  1255 non-null   int64
 15  SPY_Volume   1255 non-null   int64
dtypes: datetime64[ns](1), float64(12), int64(3)
memory usage: 157.0 KB

In [58]:
data.describe()

,Date,AAPL_Close,MSFT_Close,SPY_Close,AAPL_High,MSFT_High,SPY_High,AAPL_Low,MSFT_Low,SPY_Low,AAPL_Open,MSFT_Open,SPY_Open,AAPL_Volume,MSFT_Volume,SPY_Volume
count,1255,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0,1255.0
mean,2023-12-25 08:50:06.215139584,193.0,358.0,499.0,195.0,362.0,502.0,191.0,355.0,496.0,193.0,358.0,499.0,65309021.0,26484705.0,75688749.0
min,2021-06-28 00:00:00,123.0,208.0,339.0,126.0,214.0,342.0,122.0,207.0,331.0,124.0,211.0,332.0,17910600.0,5855900.0,26048700.0
25%,2022-09-24 12:00:00,156.0,282.0,407.0,159.0,284.0,409.0,154.0,279.0,403.0,156.0,282.0,406.0,45795050.0,19018600.0,56542700.0
50%,2023-12-22 00:00:00,182.0,366.0,458.0,184.0,369.0,459.0,181.0,362.0,455.0,182.0,365.0,457.0,57305700.0,23598800.0,71181200.0
75%,2025-03-26 12:00:00,226.0,418.0,585.0,228.0,421.0,588.0,224.0,414.0,583.0,226.0,418.0,586.0,77385500.0,30610150.0,89405150.0
max,2026-06-26 00:00:00,315.0,539.0,758.0,317.0,551.0,758.0,310.0,537.0,755.0,314.0,551.0,756.0,318679900.0,186112200.0,256611400.0
std,NaN,45.0,84.0,111.0,45.0,84.0,111.0,44.0,83.0,111.0,45.0,84.0,111.0,28729654.0,12015819.0,29102851.0

In [60]:
data.isnull().sum()

Date           0
AAPL_Close     0
MSFT_Close     0
SPY_Close      0
AAPL_High      0
MSFT_High      0
SPY_High       0
AAPL_Low       0
MSFT_Low       0
SPY_Low        0
AAPL_Open      0
MSFT_Open      0
SPY_Open       0
AAPL_Volume    0
MSFT_Volume    0
SPY_Volume     0
dtype: int64

In [ ]:
import numpy as np
price_cols = [col for col in data.columns if 'Close' in col or 'Open' in col or 'High' in col or 'Low' in col]
for col in price_cols:
    data[col] = data[col].apply(lambda x: np.nan if x <= 0 else x)
data[price_cols] = data[price_cols].ffill()

In [61]:
import pandas as pd
data = data.reset_index()
data['Date'] = pd.to_datetime(data['Date'])

In [62]:
data = data.sort_values("Date")

In [63]:
data

,index,Date,AAPL_Close,MSFT_Close,SPY_Close,AAPL_High,MSFT_High,SPY_High,AAPL_Low,MSFT_Low,SPY_Low,AAPL_Open,MSFT_Open,SPY_Open,AAPL_Volume,MSFT_Volume,SPY_Volume
0,0,2021-06-28,131.377060,257.889679,399.526550,131.835195,258.062417,399.694777,129.983172,255.192934,398.049846,130.041655,255.461648,399.246173,62111300,19590000,53159600
1,1,2021-06-29,132.887924,260.461700,399.741547,133.043888,260.701625,400.545315,130.957920,257.179554,399.208800,131.396555,258.033669,399.909773,64556100,19937800,35970500
2,2,2021-06-30,133.501999,259.981812,400.078033,133.940634,260.423264,400.750969,132.439508,258.734218,399.255554,132.731937,259.780283,399.283592,63261400,21656500,64827900
3,3,2021-07-01,133.804230,260.653595,402.293060,133.862712,260.883913,402.451960,132.332344,258.734202,400.769608,133.151148,258.743779,400.835039,52485800,16725300,53441000
4,4,2021-07-02,136.426285,266.459808,405.367981,136.465268,266.795708,405.723145,134.272077,261.517376,402.377152,134.418283,261.824486,403.452000,78852600,26458000,57697700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,1250,2026-06-22,297.010010,367.339996,744.390015,302.420013,381.630005,750.179993,296.760010,367.070007,743.130005,297.309998,375.739990,747.700012,44879900,45171100,46628100
1251,1251,2026-06-23,294.299988,373.940002,733.580017,301.640015,377.220001,739.630005,294.179993,370.670013,732.299988,297.540009,372.380005,733.809998,52010900,40647600,66846800
1252,1252,2026-06-24,293.079987,365.459991,733.239990,299.700012,378.880005,739.950012,292.940002,364.779999,730.840027,295.359985,371.570007,735.169983,53081900,44509900,57439500
1253,1253,2026-06-25,275.149994,352.829987,734.299988,288.799988,364.230011,739.369995,273.750000,349.200012,729.599976,287.399994,362.769989,738.909973,107013700,66179000,53934400
1254,1254,2026-06-26,283.779999,372.970001,728.989990,285.950012,376.609985,736.530029,274.209991,355.429993,716.580017,275.000000,357.149994,728.950012,261693600,186112200,70932800

In [65]:
data

,index,Date,AAPL_Close,MSFT_Close,SPY_Close,AAPL_High,MSFT_High,SPY_High,AAPL_Low,MSFT_Low,SPY_Low,AAPL_Open,MSFT_Open,SPY_Open,AAPL_Volume,MSFT_Volume,SPY_Volume
0,0,2021-06-28,131.377060,257.889679,399.526550,131.835195,258.062417,399.694777,129.983172,255.192934,398.049846,130.041655,255.461648,399.246173,62111300,19590000,53159600
1,1,2021-06-29,132.887924,260.461700,399.741547,133.043888,260.701625,400.545315,130.957920,257.179554,399.208800,131.396555,258.033669,399.909773,64556100,19937800,35970500
2,2,2021-06-30,133.501999,259.981812,400.078033,133.940634,260.423264,400.750969,132.439508,258.734218,399.255554,132.731937,259.780283,399.283592,63261400,21656500,64827900
3,3,2021-07-01,133.804230,260.653595,402.293060,133.862712,260.883913,402.451960,132.332344,258.734202,400.769608,133.151148,258.743779,400.835039,52485800,16725300,53441000
4,4,2021-07-02,136.426285,266.459808,405.367981,136.465268,266.795708,405.723145,134.272077,261.517376,402.377152,134.418283,261.824486,403.452000,78852600,26458000,57697700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,1250,2026-06-22,297.010010,367.339996,744.390015,302.420013,381.630005,750.179993,296.760010,367.070007,743.130005,297.309998,375.739990,747.700012,44879900,45171100,46628100
1251,1251,2026-06-23,294.299988,373.940002,733.580017,301.640015,377.220001,739.630005,294.179993,370.670013,732.299988,297.540009,372.380005,733.809998,52010900,40647600,66846800
1252,1252,2026-06-24,293.079987,365.459991,733.239990,299.700012,378.880005,739.950012,292.940002,364.779999,730.840027,295.359985,371.570007,735.169983,53081900,44509900,57439500
1253,1253,2026-06-25,275.149994,352.829987,734.299988,288.799988,364.230011,739.369995,273.750000,349.200012,729.599976,287.399994,362.769989,738.909973,107013700,66179000,53934400
1254,1254,2026-06-26,283.779999,372.970001,728.989990,285.950012,376.609985,736.530029,274.209991,355.429993,716.580017,275.000000,357.149994,728.950012,261693600,186112200,70932800

In [67]:
data=data.drop(columns=['index'])
data

,Date,AAPL_Close,MSFT_Close,SPY_Close,AAPL_High,MSFT_High,SPY_High,AAPL_Low,MSFT_Low,SPY_Low,AAPL_Open,MSFT_Open,SPY_Open,AAPL_Volume,MSFT_Volume,SPY_Volume
0,2021-06-28,131.377060,257.889679,399.526550,131.835195,258.062417,399.694777,129.983172,255.192934,398.049846,130.041655,255.461648,399.246173,62111300,19590000,53159600
1,2021-06-29,132.887924,260.461700,399.741547,133.043888,260.701625,400.545315,130.957920,257.179554,399.208800,131.396555,258.033669,399.909773,64556100,19937800,35970500
2,2021-06-30,133.501999,259.981812,400.078033,133.940634,260.423264,400.750969,132.439508,258.734218,399.255554,132.731937,259.780283,399.283592,63261400,21656500,64827900
3,2021-07-01,133.804230,260.653595,402.293060,133.862712,260.883913,402.451960,132.332344,258.734202,400.769608,133.151148,258.743779,400.835039,52485800,16725300,53441000
4,2021-07-02,136.426285,266.459808,405.367981,136.465268,266.795708,405.723145,134.272077,261.517376,402.377152,134.418283,261.824486,403.452000,78852600,26458000,57697700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,2026-06-22,297.010010,367.339996,744.390015,302.420013,381.630005,750.179993,296.760010,367.070007,743.130005,297.309998,375.739990,747.700012,44879900,45171100,46628100
1251,2026-06-23,294.299988,373.940002,733.580017,301.640015,377.220001,739.630005,294.179993,370.670013,732.299988,297.540009,372.380005,733.809998,52010900,40647600,66846800
1252,2026-06-24,293.079987,365.459991,733.239990,299.700012,378.880005,739.950012,292.940002,364.779999,730.840027,295.359985,371.570007,735.169983,53081900,44509900,57439500
1253,2026-06-25,275.149994,352.829987,734.299988,288.799988,364.230011,739.369995,273.750000,349.200012,729.599976,287.399994,362.769989,738.909973,107013700,66179000,53934400
1254,2026-06-26,283.779999,372.970001,728.989990,285.950012,376.609985,736.530029,274.209991,355.429993,716.580017,275.000000,357.149994,728.950012,261693600,186112200,70932800

Checking the validation so that the data isn't broken, corrupted or completely wrong.

In [70]:
def validate(df, filename="clean_stock_data.csv"):
  print("starting to validate the data.")
  missing_vals=data.isnull().sum().sum()
  if missing_vals>0:
    print(f"Validation failed: found {missing_vals} missing values")
    return False
  duplicate_rows=data.duplicated().sum()
  if duplicate_rows>0:
    print(f"Validation failed: found {duplicate_rows} duplicate rows")
    return False
  price_cols:[col for col in df.columns if 'Close' in col or 'Open' in col or 'High' in col or 'Volume' in col or 'Low' in col]
  for col in price_cols:
    if(df[col]<=0).any():
      print(f"Validation failed: column {col} contains negative or zero prices.")
  if 'index' in data.columns:
        print(" Validation Failed: The unwanted 'index' column is still present.")
        return False
  print("All validations passed! Data is clean.")
  data.to_csv(filename, index=False)
  print(f"File successfully saved as '{filename}'")
  return True
validate_and_save_data(data)